### ISSUE TITLE
JDK image를 교체한다

### ISSUE THREAD

**Issue by minsang-alt** [AgileHub-DQ/Backend#12]
### 🔨 Describe

도커 이미지가 총 700MB로 매우 큰 상태라 알아보는 중에 openjdk:17-ea-33-jdk-buster가 크기도 매우 크고 openjdk는 취약점이 많다는 사실을 알게되었습니다.
https://stackoverflow.com/questions/69525199/openjdk-java-17-docker-image/75997220#75997220 참고 

JDK를 지원하는 다른 이미지로 교체하겠습니다

### ✅ Tasks

- [ ] 도커 파일 수정

**Comment by Enble** [comment]
temurin 추천합니다!
