### ISSUE TITLE
Spring Security에 CORS 부분 넘기고, 리버스 프록시에서는 CORS 관련 설정 삭제

### ISSUE THREAD

**Issue by Enble** [AgileHub-DQ/Backend#36]
### 🔨 Describe

현재 Spring Security를 사용하면서, 기존 리버스 프록시에 존재하는 cors 관련 설정을 Spring Security에게로 전가하면 좋을 것 같습니다.

### ✅ Tasks

* NGINX에서 CORS 관련 설정 삭제
* Spring Security에 CORS 관련 설정 추가

**Comment by minsang-alt** [comment]
확인했습니다. 리버스프록시만 남기는 쪽으로 내일 아침에 해결하겠습니다

**Comment by minsang-alt** [comment]
프론트 API 테스트를 계속 하기 위해 CORS 설정 이후로 nginx conf파일을 수정을 하겠습니다

**Comment by Enble** [comment]
완료되었으므로, 이슈 닫습니다.
