### ISSUE TITLE
Front의 local에서 social login시 redirect를 받지 못함

### ISSUE THREAD

**Issue by Enble** [AgileHub-DQ/Backend#81]
### 🐞 Describe

Backend의 OAuth2SuccessHandler에서 redirect를 프론트 배포 서버의 주소(`www.agilehub.store`)로 수행합니다.
따라서 front local(`localhost:3000`)에서는 redirect를 받지 못하는 문제가 발생합니다.
이에 따라 프론트의 리다이렉트 페이지 구축 테스트가 불가합니다.

### 🌏 Environment

무관

**Comment by Enble** [comment]
백에서 redirect 시 request의 `getRemoteAddr()`로 요청 IP 주소를 사용하는 방법 등이 필요할 것 같습니다.
[참고](https://velog.io/@haron/Spring-%EC%B5%9C%EC%B4%88-%EC%9A%94%EC%B2%AD-IP-%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EA%B0%80%EC%A0%B8%EC%98%A4%EB%8A%94-%EA%B1%B8%EA%B9%8C-6aie0x11)

**Comment by minsang-alt** [comment]
> 백에서 redirect 시 request의 `getRemoteAddr()`로 요청 IP 주소를 사용하는 방법 등이 필요할 것 같습니다. [참고](https://velog.io/@haron/Spring-%EC%B5%9C%EC%B4%88-%EC%9A%94%EC%B2%AD-IP-%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EA%B0%80%EC%A0%B8%EC%98%A4%EB%8A%94-%EA%B1%B8%EA%B9%8C-6aie0x11)

여기서 그냥 리다이렉트 대신 Header에 넣어서 응답하면 안될까요?
```java
    @Override
    @Transactional
    public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response,
                                        Authentication authentication) throws IOException {
        log.info("OAuth2SuccessHandler.onAuthenticationSuccess");

        GeneratedToken generatedToken = generateMemberToken(authentication);
        
        response.addHeader("Authorization", "Bearer " + generatedToken.getAccessToken());

    }

```
![image](https://github.com/AgileHub-DQ/Backend/assets/82764703/e19e2e7a-dd3c-49c4-ae93-e05f53ebcad1)

**Comment by Enble** [comment]
해당 내용 정상 구현 처리되었으므로 이슈 닫습니다.
